name: First Workflow
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: "shibil"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: print welcome
        run: echo $NAME
      - name: print institution
        env:
          INSTITUTION: "Zoople"
        run: echo $INSTITUTION
      - name: test step
        run: echo $NAME
